export const homeObjOne = {
    id: "about",
    lightBg: false,
    lightText: true,
    lightTextDesc: true,
    topLine: "Acerca de",
    headLine: "¿Qué hacemos en karaoke?",
    description: "Karaoke es el servicio número uno de streaming para karaoke en Latinoamérica. ",
    buttonLabel: "Empieza ahora",
    imgStart: false,
    img: require("../../../images/secure.svg").default,
    alt: "secure",
    dark: true,
    primary: true,
    darkText: false,
  }
  
  export const homeObjTwo = {
    id: "discover",
    lightBg: true,
    lightText: false,
    lightTextDesc: false,
    topLine: "Acceso Ilimitado",
    headLine: "Inicie sesión en su cuenta en cualquier momento",
    description: "karaoke, tiene disponibilidad abierta de 99,99%. Lo tenemos cubierto sin importar dónde se encuentre. Todo lo que necesita es una conexión a Internet y un teléfono o computadora.",
    buttonLabel: "Aprende más",
    imgStart: true,
    img: require("../../../images/bank.svg").default,
    alt: "bank",
    dark: false,
    primary: false,
    darkText: true,
  }
  
  export const homeObjThree = {
    id: "services",
    lightBg: false,
    lightText: true,
    lightTextDesc: true,
    topLine: "Servicios",
    headLine: "Principales Servicios y Funciones",
    description: "Como usuario puede buscar y reproducir una canción para lo cual la aplicación Karaoke, hará streaming del  audio y sincronizará la letra para que pueda cantar al ritmo de la música",
    buttonLabel: "Iniciar Sesión",
    imgStart: false,
    img: require("../../../images/secure.svg").default,
    alt: "secure",
    dark: true,
    primary: true,
    darkText: false,
  }
  
  export const homeObjFour = {
    id: "signin",
    lightBg: true,
    lightText: false,
    lightTextDesc: false,
    topLine: "Acceso Premium",
    headLine: "Ten acceso a más de 300 canciones",
    description: "Con el acceso premium puedes tener acceso a más de 300 canciones, sugerir cambios y/o modificarlas.",
    buttonLabel: "Empieza ahora",
    imgStart: true,
    img: require("../../../images/bank.svg").default,
    alt: "bank",
    dark: false,
    primary: false,
    darkText: true,
  }